[
    {"start_year": 1996, "end_year": 2016, "name": "Kevin Garnett", "position": "F-C"},
    {"start_year": 1985, "end_year": 2000, "name": "Charles Barkley", "position": "F"},
    {"start_year": 1987, "end_year": 2000, "name": "Dennis Rodman", "position": "F"},
    {"start_year": 1985, "end_year": 2002, "name": "Hakeem Olajuwon", "position": "C"},
    {"start_year": 1995, "end_year": 2013, "name": "Jason Kidd", "position": "G"},
    {"start_year": 1997, "end_year": 2010, "name": "Allen Iverson", "position": "G"},
    {"start_year": 2003, "end_year": 2011, "name": "Yao Ming", "position": "C"},
    {"start_year": 1997, "end_year": 2016, "name": "Kobe Bryant", "position": "G-F"},
    {"start_year": 1990, "end_year": 2003, "name": "David Robinson", "position": "C"},
    {"start_year": 1988, "end_year": 2004, "name": "Scottie Pippen", "position": "F-G"},
    {"start_year": 1993, "end_year": 2011, "name": "Shaquille O'Neal", "position": "C"},
    {
        "start_year": 1994,
        "end_year": 2008,
        "name": "Anfernee Hardaway",
        "position": "G-F",
    },
    {"start_year": 1986, "end_year": 2002, "name": "Patrick Ewing", "position": "C-F"},
    {"start_year": 1990, "end_year": 2003, "name": "Shawn Kemp", "position": "F-C"},
    {"start_year": 1992, "end_year": 2001, "name": "Larry Johnson", "position": "F"},
    {"start_year": 1980, "end_year": 1992, "name": "Larry Bird", "position": "F"},
    {"start_year": 1971, "end_year": 1980, "name": "Pete Maravich", "position": "G"},
    {"start_year": 1960, "end_year": 1973, "name": "Wilt Chamberlain", "position": "C"},
    {"start_year": 1986, "end_year": 2004, "name": "Karl Malone", "position": "F"},
    {
        "start_year": 1970,
        "end_year": 1989,
        "name": "Kareem Abdul-Jabbar",
        "position": "C",
    },
    {"start_year": 1957, "end_year": 1969, "name": "Bill Russell", "position": "C"},
    {"start_year": 1997, "end_year": 2014, "name": "Ray Allen", "position": "G"},
    {"start_year": 1984, "end_year": 1998, "name": "Clyde Drexler", "position": "G"},
    {"start_year": 1995, "end_year": 2013, "name": "Grant Hill", "position": "F-G"},
    {"start_year": 1980, "end_year": 1996, "name": "Magic Johnson", "position": "G-F"},
    {"start_year": 1998, "end_year": 2012, "name": "Tracy McGrady", "position": "F-G"},
    {"start_year": 1993, "end_year": 2008, "name": "Alonzo Mourning", "position": "C"},
    {"start_year": 1997, "end_year": 2014, "name": "Steve Nash", "position": "G"},
    {"start_year": 1999, "end_year": 2017, "name": "Paul Pierce", "position": "F-G"},
    {"start_year": 1982, "end_year": 1994, "name": "Isiah Thomas", "position": "G"},
    {"start_year": 2015, "end_year": None, "name": "Tyler Johnson", "position": "G"},
    {
        "start_year": 2011,
        "end_year": None,
        "name": "DeMarcus Cousins",
        "position": "C-F",
    },
    {"start_year": 2012, "end_year": None, "name": "Chandler Parsons", "position": "F"},
    {"start_year": 2013, "end_year": None, "name": "Dion Waiters", "position": "G"},
    {"start_year": 2012, "end_year": None, "name": "Isaiah Thomas", "position": "G"},
    {"start_year": 2002, "end_year": None, "name": "Pau Gasol", "position": "F-C"},
    {"start_year": 2020, "end_year": None, "name": "Chuma Okeke", "position": "F"},
    {"start_year": 2020, "end_year": None, "name": "Jaylen Hands", "position": "G"},
    {
        "start_year": 2019,
        "end_year": None,
        "name": "Deividas Sirvydis",
        "position": "G-F",
    },
    {"start_year": 1972, "end_year": 1987, "name": "Julius Erving", "position": "F-G"},
    {"start_year": 1999, "end_year": 2019, "name": "Dirk Nowitzki", "position": "F"},
    {"start_year": 1994, "end_year": 2004, "name": "Jamal Mashburn", "position": "F"},
    {"start_year": 1989, "end_year": 2002, "name": "John Starks", "position": "G"},
    {
        "start_year": 1998,
        "end_year": 2003,
        "name": "Tariq Abdul-Wahad",
        "position": "F",
    },
    {"start_year": 1993, "end_year": 2005, "name": "Latrell Sprewell", "position": "G"},
    {"start_year": 1987, "end_year": 1998, "name": "Nate McMillan", "position": "G-F"},
    {"start_year": 1985, "end_year": 2003, "name": "John Stockton", "position": "G"},
    {"start_year": 2003, "end_year": 2016, "name": "Caron Butler", "position": "F"},
    {"start_year": 1992, "end_year": 2005, "name": "Kenny Anderson", "position": "G"},
    {"start_year": 1986, "end_year": 1998, "name": "Xavier McDaniel", "position": "F"},
    {"start_year": 1982, "end_year": 1998, "name": "Tom Chambers", "position": "F-C"},
    {
        "start_year": 1961,
        "end_year": 1974,
        "name": "Oscar Robertson",
        "position": "G-F",
    },
    {"start_year": 1991, "end_year": 2000, "name": "Dennis Scott", "position": "F"},
    {"start_year": 1970, "end_year": 1982, "name": "Bob Dandridge", "position": "F-G"},
    {"start_year": 1999, "end_year": 2010, "name": "Ricky Davis", "position": "G"},
    {"start_year": 2004, "end_year": 2019, "name": "Dwyane Wade", "position": "G"},
    {"start_year": 1978, "end_year": 1988, "name": "Cedric Maxwell", "position": "F"},
    {"start_year": 1994, "end_year": 1997, "name": "Dino Radja", "position": "C-F"},
    {"start_year": 1987, "end_year": 1998, "name": "Mark Price", "position": "G"},
    {"start_year": 1977, "end_year": 1991, "name": "Adrian Dantley", "position": "F-G"},
    {"start_year": 1983, "end_year": 1994, "name": "Fat Lever", "position": "G"},
    {"start_year": 1983, "end_year": 1994, "name": "James Worthy", "position": "F"},
    {
        "start_year": 1979,
        "end_year": 1991,
        "name": "Mychal Thompson",
        "position": "C-F",
    },
    {"start_year": 1989, "end_year": 2002, "name": "Dan Majerle", "position": "G-F"},
    {"start_year": 2000, "end_year": 2008, "name": "Steve Francis", "position": "G"},
    {
        "start_year": 1983,
        "end_year": 1999,
        "name": "Dominique Wilkins",
        "position": "F-G",
    },
    {"start_year": 1998, "end_year": 2016, "name": "Tim Duncan", "position": "F-C"},
    {"start_year": 1988, "end_year": 2004, "name": "Mark Jackson", "position": "G"},
    {"start_year": 1977, "end_year": 1986, "name": "Quinn Buckner", "position": "G"},
    {"start_year": 2004, "end_year": 2013, "name": "Luke Walton", "position": "F"},
    {"start_year": 1996, "end_year": 2013, "name": "Kurt Thomas", "position": "F"},
    {"start_year": 1981, "end_year": 1993, "name": "Kevin McHale", "position": "F-C"},
    {"start_year": 2000, "end_year": 2009, "name": "Wally Szczerbiak", "position": "F"},
    {"start_year": 1981, "end_year": 1999, "name": "Rick Mahorn", "position": "C-F"},
    {"start_year": 1992, "end_year": 2001, "name": "Luc Longley", "position": "C"},
    {"start_year": 2002, "end_year": 2019, "name": "Tony Parker", "position": "G"},
    {"start_year": 1998, "end_year": 2011, "name": "Antonio Daniels", "position": "G"},
    {"start_year": 1982, "end_year": 1991, "name": "Kelly Tripucka", "position": "F-G"},
    {"start_year": 1976, "end_year": 1988, "name": "World B. Free", "position": "G"},
    {"start_year": 2001, "end_year": 2009, "name": "Stromile Swift", "position": "F"},
    {"start_year": 1986, "end_year": 2001, "name": "A.C. Green", "position": "F-C"},
    {"start_year": 1961, "end_year": 1974, "name": "Jerry West", "position": "G"},
    {
        "start_year": 1979,
        "end_year": 1986,
        "name": "Micheal Ray Richardson",
        "position": "G-F",
    },
    {"start_year": 1997, "end_year": 2009, "name": "Bruce Bowen", "position": "F"},
    {"start_year": 2006, "end_year": 2019, "name": "Channing Frye", "position": "C-F"},
    {"start_year": 1989, "end_year": 2001, "name": "Will Perdue", "position": "C"},
    {"start_year": 1973, "end_year": 1986, "name": "Bob McAdoo", "position": "C-F"},
    {"start_year": 1989, "end_year": 2000, "name": "Rik Smits", "position": "C"},
    {
        "start_year": 2001,
        "end_year": 2013,
        "name": "Quentin Richardson",
        "position": "G",
    },
    {"start_year": 2001, "end_year": 2009, "name": "Darius Miles", "position": "F"},
    {"start_year": 1989, "end_year": 2003, "name": "Danny Manning", "position": "F-C"},
    {"start_year": 1976, "end_year": 1985, "name": "M.L. Carr", "position": "F-G"},
    {"start_year": 1971, "end_year": 1985, "name": "Dan Issel", "position": "C-F"},
    {"start_year": 2000, "end_year": 2018, "name": "Jason Terry", "position": "G"},
    {"start_year": 1982, "end_year": 1995, "name": "Kurt Rambis", "position": "F"},
    {"start_year": 1998, "end_year": 2006, "name": "Keith Van Horn", "position": "F"},
    {"start_year": 1994, "end_year": 2005, "name": "Shawn Bradley", "position": "C"},
    {"start_year": 1995, "end_year": 2008, "name": "Eddie Jones", "position": "G-F"},
    {"start_year": 1989, "end_year": 2003, "name": "Steve Kerr", "position": "G"},
    {
        "start_year": 2020,
        "end_year": None,
        "name": "Justin Wright-Foreman",
        "position": "G",
    },
    {"start_year": 2000, "end_year": 2010, "name": "Devean George", "position": "G-F"},
    {"start_year": 1993, "end_year": 2007, "name": "Doug Christie", "position": "G-F"},
    {"start_year": 1976, "end_year": 1988, "name": "Alvan Adams", "position": "C-F"},
    {"start_year": 1967, "end_year": 1977, "name": "Jack Marin", "position": "F-G"},
    {
        "start_year": 1972,
        "end_year": 1982,
        "name": "George McGinnis",
        "position": "F-C",
    },
    {"start_year": 1968, "end_year": 1976, "name": "Pat Riley", "position": "G-F"},
    {"start_year": 1978, "end_year": 1993, "name": "Bernard King", "position": "F"},
    {"start_year": 1985, "end_year": 2007, "name": "Kevin Willis", "position": "F-C"},
    {"start_year": 2003, "end_year": 2015, "name": "Carlos Boozer", "position": "F-C"},
    {"start_year": 2020, "end_year": None, "name": "Zach Norvell Jr.", "position": "G"},
    {"start_year": 1994, "end_year": 2008, "name": "Sam Cassell", "position": "G"},
    {"start_year": 1995, "end_year": 2013, "name": "Juwan Howard", "position": "F"},
    {"start_year": 2018, "end_year": None, "name": "Tyrone Wallace", "position": "G"},
    {"start_year": 2018, "end_year": None, "name": "Antonio Blakeney", "position": "G"},
    {"start_year": 1995, "end_year": 2007, "name": "Jalen Rose", "position": "G-F"},
    {"start_year": 1978, "end_year": 1992, "name": "Brad Davis", "position": "G"},
    {"start_year": 1966, "end_year": 1980, "name": "Rick Barry", "position": "F"},
    {"start_year": 1990, "end_year": 2004, "name": "Dana Barros", "position": "G"},
    {"start_year": 1976, "end_year": 1985, "name": "Lionel Hollins", "position": "G"},
    {"start_year": 1979, "end_year": 1993, "name": "Maurice Cheeks", "position": "G"},
    {"start_year": 1994, "end_year": 2006, "name": "Nick Van Exel", "position": "G"},
    {"start_year": 1977, "end_year": 1991, "name": "Alex English", "position": "F"},
    {"start_year": 1969, "end_year": 1980, "name": "Don Chaney", "position": "G"},
    {"start_year": 1978, "end_year": 1989, "name": "Otis Birdsong", "position": "G"},
    {"start_year": 2004, "end_year": 2016, "name": "Chris Bosh", "position": "F-C"},
    {"start_year": 2001, "end_year": 2012, "name": "Raja Bell", "position": "G"},
    {"start_year": 1987, "end_year": 1995, "name": "Kenny Walker", "position": "F"},
    {"start_year": 1997, "end_year": 2008, "name": "Antoine Walker", "position": "F"},
    {"start_year": 1961, "end_year": 1975, "name": "Lenny Wilkens", "position": "G"},
    {"start_year": 1996, "end_year": 2003, "name": "Arvydas Sabonis", "position": "C"},
    {"start_year": 1971, "end_year": 1984, "name": "Bob Lanier", "position": "C"},
    {"start_year": 1999, "end_year": 2009, "name": "Tyronn Lue", "position": "G"},
    {"start_year": 1979, "end_year": 1990, "name": "Michael Cooper", "position": "G-F"},
    {"start_year": 1994, "end_year": 2006, "name": "Toni Kukoc", "position": "F"},
    {"start_year": 1959, "end_year": 1972, "name": "Elgin Baylor", "position": "F"},
    {"start_year": 1981, "end_year": 1993, "name": "Kiki Vandeweghe", "position": "F"},
    {"start_year": 1998, "end_year": 2002, "name": "Felipe Lopez", "position": "G"},
    {"start_year": 1999, "end_year": 2009, "name": "Cuttino Mobley", "position": "G"},
    {"start_year": 2006, "end_year": None, "name": "Gerald Green", "position": "G-F"},
    {"start_year": 2020, "end_year": None, "name": "Justin Robinson", "position": "G"},
    {"start_year": 1998, "end_year": 2014, "name": "Chauncey Billups", "position": "G"},
    {"start_year": 1977, "end_year": 1997, "name": "Robert Parish", "position": "C"},
    {"start_year": 1971, "end_year": 1983, "name": "Calvin Murphy", "position": "G"},
    {"start_year": 1968, "end_year": 1979, "name": "Louie Dampier", "position": "G"},
    {"start_year": 1978, "end_year": 1995, "name": "Tree Rollins", "position": "C"},
    {"start_year": 2002, "end_year": 2014, "name": "Shane Battier", "position": "F"},
    {
        "start_year": 1993,
        "end_year": 2005,
        "name": "Christian Laettner",
        "position": "F-C",
    },
    {"start_year": 1999, "end_year": 2014, "name": "Rashard Lewis", "position": "F"},
    {"start_year": 1988, "end_year": 1997, "name": "Kenny Smith", "position": "G"},
    {"start_year": 1995, "end_year": 2005, "name": "Charlie Ward", "position": "G"},
    {"start_year": 1971, "end_year": 1980, "name": "Charlie Scott", "position": "G-F"},
    {"start_year": 1972, "end_year": 1988, "name": "Artis Gilmore", "position": "C"},
    {
        "start_year": 1996,
        "end_year": 2011,
        "name": "Antonio McDyess",
        "position": "F-C",
    },
    {"start_year": 1973, "end_year": 1986, "name": "George Gervin", "position": "G-F"},
    {"start_year": 1990, "end_year": 2004, "name": "Glen Rice", "position": "F"},
    {"start_year": 2019, "end_year": None, "name": "Daryl Macon", "position": "G"},
    {"start_year": 2019, "end_year": None, "name": "Ryan Broekhoff", "position": "F"},
    {"start_year": 2019, "end_year": None, "name": "Jonah Bolden", "position": "F"},
    {"start_year": 1986, "end_year": 1999, "name": "Joe Dumars", "position": "G"},
    {"start_year": 1975, "end_year": 1995, "name": "Moses Malone", "position": "C-F"},
    {"start_year": 1995, "end_year": 2011, "name": "Joe Smith", "position": "F"},
    {"start_year": 1996, "end_year": 2014, "name": "Derek Fisher", "position": "G"},
]
