[
    {"start_year": 2012, "end_year": None, "name": "Andrew Luck", "position": "QB"},
    {"start_year": 2010, "end_year": 2018, "name": "Rob Gronkowski", "position": "TE"},
    {
        "start_year": 2014,
        "end_year": None,
        "name": "DeMarcus Lawrence",
        "position": "DE",
    },
    {"start_year": 2002, "end_year": 2010, "name": "Brian Westbrook", "position": "RB"},
    {"start_year": 2016, "end_year": None, "name": "Josh Doctson", "position": "WR"},
    {
        "start_year": 2018,
        "end_year": None,
        "name": "Antonio Callaway",
        "position": "WR",
    },
    {"start_year": 1991, "end_year": 2010, "name": "Brett Favre", "position": "QB"},
    {"start_year": 1998, "end_year": 2015, "name": "Peyton Manning", "position": "QB"},
    {"start_year": 1956, "end_year": 1973, "name": "Johnny Unitas", "position": "QB"},
    {"start_year": 1998, "end_year": 2010, "name": "Fred Taylor", "position": "RB"},
    {"start_year": 2007, "end_year": None, "name": "Greg Olsen", "position": "TE"},
    {"start_year": 2010, "end_year": None, "name": "Antonio Brown", "position": "WR"},
    {"start_year": 1985, "end_year": 1999, "name": "Steve Young", "position": "QB"},
    {"start_year": 1986, "end_year": 1996, "name": "Jim Kelly", "position": "QB"},
    {"start_year": 1988, "end_year": 2000, "name": "Thurman Thomas", "position": "RB"},
    {"start_year": 1983, "end_year": 1999, "name": "Dan Marino", "position": "QB"},
    {"start_year": 1993, "end_year": 2006, "name": "Drew Bledsoe", "position": "QB"},
    {"start_year": 1965, "end_year": 1977, "name": "Joe Namath", "position": "QB"},
    {"start_year": 1995, "end_year": 2005, "name": "Curtis Martin", "position": "RB"},
    {"start_year": 1969, "end_year": 1979, "name": "Roger Staubach", "position": "QB"},
    {"start_year": 1997, "end_year": 2006, "name": "Tiki Barber", "position": "RB"},
    {"start_year": 2002, "end_year": 2010, "name": "Clinton Portis", "position": "RB"},
    {"start_year": 1996, "end_year": 2012, "name": "Ray Lewis", "position": "LB"},
    {"start_year": 2002, "end_year": 2013, "name": "Ed Reed", "position": "DB"},
    {"start_year": 1989, "end_year": 1998, "name": "Barry Sanders", "position": "RB"},
    {"start_year": 2007, "end_year": 2015, "name": "Calvin Johnson", "position": "WR"},
    {"start_year": 1998, "end_year": 2001, "name": "Pat Tillman", "position": "DB"},
    {"start_year": 1998, "end_year": 2009, "name": "Kurt Warner", "position": "QB"},
    {"start_year": 1987, "end_year": 1990, "name": "Bo Jackson", "position": "RB"},
    {"start_year": 1988, "end_year": 2004, "name": "Tim Brown", "position": "WR"},
    {"start_year": 1984, "end_year": 2000, "name": "Warren Moon", "position": "QB"},
    {"start_year": 1996, "end_year": 2004, "name": "Eddie George", "position": "RB"},
    {"start_year": 2000, "end_year": 2008, "name": "Shaun Alexander", "position": "RB"},
    {"start_year": 1976, "end_year": 1989, "name": "Steve Largent", "position": "WR"},
    {"start_year": 1993, "end_year": 2005, "name": "Jerome Bettis", "position": "RB"},
    {"start_year": 1970, "end_year": 1983, "name": "Terry Bradshaw", "position": "QB"},
    {"start_year": 1985, "end_year": 2004, "name": "Jerry Rice", "position": "WR"},
    {"start_year": 2000, "end_year": 2012, "name": "Brian Urlacher", "position": "LB"},
    {"start_year": 1965, "end_year": 1973, "name": "Dick Butkus", "position": "LB"},
    {"start_year": 1983, "end_year": 1998, "name": "John Elway", "position": "QB"},
    {"start_year": 1995, "end_year": 2001, "name": "Terrell Davis", "position": "RB"},
    {"start_year": 1979, "end_year": 1994, "name": "Joe Montana", "position": "QB"},
    {"start_year": 1981, "end_year": 1993, "name": "Lawrence Taylor", "position": "LB"},
    {"start_year": 1998, "end_year": 2012, "name": "Randy Moss", "position": "WR"},
    {"start_year": 1989, "end_year": 2005, "name": "Deion Sanders", "position": "DB"},
    {"start_year": 1995, "end_year": 2007, "name": "Warren Sapp", "position": "DT"},
    {"start_year": 1971, "end_year": 1984, "name": "Archie Manning", "position": "QB"},
    {"start_year": 2001, "end_year": 2015, "name": "Michael Vick", "position": "QB"},
    {"start_year": 1998, "end_year": 2011, "name": "Hines Ward", "position": "WR"},
    {
        "start_year": 2001,
        "end_year": 2011,
        "name": "LaDainian Tomlinson",
        "position": "RB",
    },
    {"start_year": 1999, "end_year": 2013, "name": "Champ Bailey", "position": "DB"},
    {"start_year": 1995, "end_year": 2008, "name": "Derrick Brooks", "position": "LB"},
    {"start_year": 1994, "end_year": 2005, "name": "Marshall Faulk", "position": "RB"},
    {"start_year": 1994, "end_year": 2008, "name": "Rodney Harrison", "position": "DB"},
    {"start_year": 1989, "end_year": 1999, "name": "Daryl Johnston", "position": "RB"},
    {"start_year": 1984, "end_year": 1997, "name": "Boomer Esiason", "position": "QB"},
    {"start_year": 1982, "end_year": 2007, "name": "Morten Andersen", "position": "K"},
    {"start_year": 1981, "end_year": 1992, "name": "Mike Singletary", "position": "LB"},
    {"start_year": 1968, "end_year": 1980, "name": "Rocky Bleier", "position": "RB"},
    {"start_year": 2004, "end_year": 2013, "name": "Willis McGahee", "position": "RB"},
    {"start_year": 2001, "end_year": 2014, "name": "Reggie Wayne", "position": "WR"},
    {"start_year": 1988, "end_year": 2003, "name": "Bill Romanowski", "position": "LB"},
    {"start_year": 1988, "end_year": 2000, "name": "Neil Smith", "position": "DE"},
    {"start_year": 1988, "end_year": 1999, "name": "Michael Irvin", "position": "WR"},
    {"start_year": 1987, "end_year": 2003, "name": "Rod Woodson", "position": "DB"},
    {"start_year": 1994, "end_year": 2009, "name": "Isaac Bruce", "position": "WR"},
    {"start_year": 2006, "end_year": 2016, "name": "Devin Hester", "position": "WR"},
    {"start_year": 1998, "end_year": 2009, "name": "Ahman Green", "position": "RB"},
    {
        "start_year": 1990,
        "end_year": 2001,
        "name": "Tony Siragusa",
        "position": "DT-NT",
    },
    {"start_year": 2002, "end_year": 2018, "name": "Julius Peppers", "position": "DE"},
    {"start_year": 1990, "end_year": 2004, "name": "Emmitt Smith", "position": "RB"},
    {"start_year": 2019, "end_year": 2019, "name": "Tyree Jackson", "position": "QB"},
    {"start_year": 2019, "end_year": 2019, "name": "Alex Barnes", "position": "RB"},
    {"start_year": 2019, "end_year": None, "name": "Terry Godwin II", "position": "WR"},
    {"start_year": 2013, "end_year": None, "name": "C.J. Anderson", "position": "RB"},
    {"start_year": 1996, "end_year": 2011, "name": "Brian Dawkins", "position": "DB"},
    {"start_year": 0, "end_year": 0, "name": "Erin Andrews", "position": "NONE"},
    {"start_year": 0, "end_year": 0, "name": "Rob Riggle", "position": "NONE"},
    {"start_year": 0, "end_year": 0, "name": "Melissa Baker", "position": "NONE"},
    {"start_year": 1997, "end_year": 2011, "name": "Jason Taylor", "position": "DE"},
    {"start_year": 1957, "end_year": 1975, "name": "Len Dawson", "position": "QB"},
    {"start_year": 1971, "end_year": 1985, "name": "John Riggins", "position": "RB"},
    {"start_year": 1960, "end_year": 1974, "name": "Jim Otto", "position": "C"},
    {
        "start_year": 1985,
        "end_year": 2001,
        "name": "Randall Cunningham",
        "position": "QB",
    },
    {"start_year": 1997, "end_year": 2013, "name": "Tony Gonzalez", "position": "TE"},
    {"start_year": 1974, "end_year": 1984, "name": "Jack Lambert", "position": "LB"},
    {"start_year": 1957, "end_year": 1965, "name": "Jim Brown", "position": "FB"},
    {"start_year": 1993, "end_year": 2007, "name": "John Lynch", "position": "DB"},
    {"start_year": 1985, "end_year": 1999, "name": "Kevin Greene", "position": "LB-DB"},
    {"start_year": 2002, "end_year": 2014, "name": "Brett Keisel", "position": "DE"},
    {
        "start_year": 1968,
        "end_year": 1981,
        "name": "Curley Culp",
        "position": "DT-NT-G",
    },
    {"start_year": 1992, "end_year": 2002, "name": "Desmond Howard", "position": "WR"},
    {
        "start_year": 2000,
        "end_year": 2018,
        "name": "Sebastian Janikowski",
        "position": "K",
    },
    {"start_year": 1985, "end_year": 2003, "name": "Bruce Smith", "position": "DE"},
    {"start_year": 1993, "end_year": 2007, "name": "Michael Strahan", "position": "DE"},
    {"start_year": 1981, "end_year": 1993, "name": "Howie Long", "position": "DE-NT"},
    {"start_year": 1996, "end_year": 2006, "name": "Mike Alstott", "position": "RB"},
    {"start_year": 1973, "end_year": 1987, "name": "Dan Fouts", "position": "QB"},
    {
        "start_year": 1983,
        "end_year": 2001,
        "name": "Bruce Matthews",
        "position": "G-C-T",
    },
    {"start_year": 1989, "end_year": 2000, "name": "Troy Aikman", "position": "QB"},
    {"start_year": 1978, "end_year": 1990, "name": "Ozzie Newsome", "position": "TE"},
    {
        "start_year": 1996,
        "end_year": 2006,
        "name": "Keyshawn Johnson",
        "position": "WR",
    },
    {"start_year": 2008, "end_year": 2018, "name": "Chris Long", "position": "DE"},
    {"start_year": 2004, "end_year": 2016, "name": "Tony Romo", "position": "QB"},
    {"start_year": 1988, "end_year": 2001, "name": "Mark Rypien", "position": "QB"},
    {"start_year": 1997, "end_year": 2012, "name": "Ronde Barber", "position": "DB"},
    {"start_year": 1974, "end_year": 1985, "name": "Joe Theismann", "position": "QB"},
    {"start_year": 1978, "end_year": 1993, "name": "James Lofton", "position": "WR"},
    {"start_year": 1986, "end_year": 1998, "name": "Keith Byars", "position": "RB-TE"},
    {"start_year": 1967, "end_year": 1980, "name": "Bob Griese", "position": "QB"},
    {
        "start_year": 1985,
        "end_year": 1999,
        "name": "Chris Doleman",
        "position": "DE-LB",
    },
    {"start_year": 1961, "end_year": 1974, "name": "Bob Lilly", "position": "DT-DE"},
    {"start_year": 1990, "end_year": 2003, "name": "John Randle", "position": "DT-DE"},
    {"start_year": 1991, "end_year": 1999, "name": "Merton Hanks", "position": "DB"},
    {"start_year": 1999, "end_year": 2009, "name": "Jevon Kearse", "position": "DE"},
    {"start_year": 1990, "end_year": 1994, "name": "Randy White", "position": "F"},
    {"start_year": 1971, "end_year": 1986, "name": "Jim Plunkett", "position": "QB"},
    {"start_year": 1979, "end_year": 1988, "name": "Mark Gastineau", "position": "DE"},
    {"start_year": 1988, "end_year": 1997, "name": "Chris Spielman", "position": "LB"},
    {"start_year": 2005, "end_year": 2015, "name": "Heath Miller", "position": "TE"},
    {"start_year": 1996, "end_year": 2008, "name": "Tedy Bruschi", "position": "LB"},
    {"start_year": 1995, "end_year": 2009, "name": "Ty Law", "position": "DB"},
    {"start_year": 1977, "end_year": 1988, "name": "Tony Dorsett", "position": "RB"},
    {"start_year": 1978, "end_year": 1985, "name": "Earl Campbell", "position": "RB"},
    {"start_year": 1985, "end_year": 2000, "name": "Andre Reed", "position": "WR"},
    {"start_year": 1979, "end_year": 1990, "name": "Dan Hampton", "position": "DE-DT"},
    {"start_year": 1961, "end_year": 1978, "name": "Fran Tarkenton", "position": "QB"},
    {"start_year": 1998, "end_year": 2015, "name": "Charles Woodson", "position": "DB"},
    {"start_year": 1964, "end_year": 1979, "name": "Paul Krause", "position": "DB-WR"},
    {"start_year": 1967, "end_year": 1981, "name": "Alan Page", "position": "DT"},
    {
        "start_year": 1958,
        "end_year": 1973,
        "name": "Don Maynard",
        "position": "E-FL-HB",
    },
    {"start_year": 1975, "end_year": 1990, "name": "Steve Grogan", "position": "QB"},
    {"start_year": 1983, "end_year": 1993, "name": "Eric Dickerson", "position": "RB"},
    {"start_year": 1976, "end_year": 1987, "name": "Jim Zorn", "position": "QB"},
    {"start_year": 2003, "end_year": 2018, "name": "Antonio Gates", "position": "TE"},
    {"start_year": 1999, "end_year": 2009, "name": "Torry Holt", "position": "WR"},
    {"start_year": 2009, "end_year": 2016, "name": "Pat McAfee", "position": "P"},
    {"start_year": 1976, "end_year": 1988, "name": "Harry Carson", "position": "LB"},
    {"start_year": 1988, "end_year": 1991, "name": "Ickey Woods", "position": "RB"},
    {"start_year": 2002, "end_year": 2017, "name": "Dwight Freeney", "position": "DE"},
    {"start_year": 2002, "end_year": 2011, "name": "Jeremy Shockey", "position": "TE"},
    {"start_year": 2004, "end_year": 2015, "name": "Steven Jackson", "position": "RB"},
    {"start_year": 1985, "end_year": 1996, "name": "Bernie Kosar", "position": "QB"},
    {"start_year": 2007, "end_year": 2014, "name": "Patrick Willis", "position": "LB"},
    {"start_year": 2008, "end_year": 2017, "name": "Cliff Avril", "position": "DE"},
    {"start_year": 1987, "end_year": 2004, "name": "Rich Gannon", "position": "QB"},
    {"start_year": 1983, "end_year": 2002, "name": "Darrell Green", "position": "DB"},
    {"start_year": 1988, "end_year": 2001, "name": "Randall McDaniel", "position": "G"},
    {"start_year": 1989, "end_year": 1999, "name": "Steve Atwater", "position": "DB"},
    {"start_year": 1999, "end_year": 2009, "name": "Edgerrin James", "position": "RB"},
    {
        "start_year": 1986,
        "end_year": 1999,
        "name": "Charles Haley",
        "position": "DE-LB",
    },
    {"start_year": 1969, "end_year": 1983, "name": "Ted Hendricks", "position": "LB"},
    {"start_year": 1971, "end_year": 1982, "name": "Jack Ham", "position": "LB"},
    {"start_year": 1983, "end_year": 1993, "name": "Roger Craig", "position": "RB"},
    {"start_year": 1983, "end_year": 1997, "name": "Bill Bates", "position": "DB"},
    {"start_year": 2002, "end_year": 2017, "name": "James Harrison", "position": "LB"},
    {"start_year": 1987, "end_year": 1992, "name": "Christian Okoye", "position": "RB"},
    {"start_year": 1999, "end_year": 2011, "name": "Ricky Williams", "position": "RB"},
    {"start_year": 1996, "end_year": 2008, "name": "Zach Thomas", "position": "LB"},
    {"start_year": 2010, "end_year": 2017, "name": "Kam Chancellor", "position": "DB"},
    {"start_year": 1980, "end_year": 1984, "name": "Billy Sims", "position": "RB"},
    {
        "start_year": 1962,
        "end_year": 1972,
        "name": "Lance Alworth",
        "position": "FL-WR",
    },
    {"start_year": 1961, "end_year": 1972, "name": "Mike Ditka", "position": "TE"},
    {"start_year": 1983, "end_year": 1993, "name": "Mark Clayton", "position": "WR"},
    {"start_year": 1987, "end_year": 1989, "name": "Brian Bosworth", "position": "LB"},
    {"start_year": 1975, "end_year": 1987, "name": "Walter Payton", "position": "RB"},
    {
        "start_year": 1961,
        "end_year": 1976,
        "name": "Jimmy Johnson",
        "position": "DB-HB",
    },
]
